### ISSUE TITLE
Fix outputs for old onset algorithm in maproom

### ISSUE THREAD

**Issue by drewmresnick** [iridl/x24-vector#18]
Upon further investigation, the plot and table produced through ingrid are not updating (seem to be static values).

In order to compare the outputs of the new and old onset functions this must be fixed so they are properly updating.

**Comment by aaron-kaplan** [comment]
I don't entirely follow. @drewmresnick @kgraaf could you figure this out together?

**Comment by aaron-kaplan** [comment]
If I understand correctly, this is no longer relevant.
